name: Orihost Auto Renew

on:
  schedule:
    - cron: '0 0 */3 * *' 
  workflow_dispatch:      

jobs:
  renew-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # 升级到 v4

      - name: Set up Python
        uses: actions/setup-python@v5 # 升级到 v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install undetected-chromedriver selenium requests

      - name: Run Script
        env:
          ORIHOST_USER: ${{ secrets.ORIHOST_USER }}
          ORIHOST_PASS: ${{ secrets.ORIHOST_PASS }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python ori_app.py

      # 如果您想删除，直接删掉下面这几行
      - name: Upload Error Screenshot
        if: failure()
        uses: actions/upload-artifact@v4 # 升级到 v4
        with:
          name: error-screenshot
          path: error_screenshot.png
